name : Continuous Integration (CI)

## Run CI jobs on all branches by default
on :
  push:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps :
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Set gradlew as executable
        run: chmod +x ./gradlew
      - name: Run unit tests
        run: ./gradlew test

  sonarcloud:
    name: SonarCloud analysis
    runs-on: ubuntu-latest
    needs: test  # Ensure that tests are completed before running SonarCloud analysis
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"  # Ensure you're using Java 17 or later
          cache: "false"  # Disable caching to ensure fresh analysis
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}