name: JaCoCo Code Coverage Reporter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-coverage-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.9
        with:
          coverage_results_path: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml  # Adjust the path to your JaCoCo XML report
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80  # Adjust minimum coverage percentage as needed
          fail_below_threshold: false
          publish_only_summary: false

      - name: Add Coverage Job Summary
        if: ${{ steps.jacoco_reporter.outputs.coverage_percentage }} != null
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY
